version: "3"
services:
  fastapi:
    build: .
    command: uvicorn --host 0.0.0.0 app.main:app --reload
    ports:
      - 8000:8000
    volumes:
      - .:/code/workspace
    networks:
      - todo_fastapi_default
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.2-alpine
    command: -c log_statement=all
    ports:
      - 5432:5432
    environment:
      POSTGRES_SERVER: db
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - todo_fastapi_default

volumes:
  db-volume:

networks:
  todo_fastapi_default:
